{{- if .Values.configMap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}
data:
{{- with .Values.configMap.data }}
    {{- toYaml . | nindent 2 }}
{{- end }}
{{- end -}}
