apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
    ephoc: "{{ .Values.ephoc }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        ephoc: "{{ .Values.ephoc }}"
    spec:
      containers:
      - name: {{.Values.appName}}
        image: 633788536644.dkr.ecr.us-east-1.amazonaws.com/{{.Values.appName}}



